import {BusinessError} from "@ohos.base";
import * as mate from "mate";
import bar from "mate"; // Test export default
import * as nova from "nova";
import NovaType from "nova"; // Test export default
import * as pura from "pura";

loadLibrary("ani_import");

function main() {
    // Intentially left blank.
    // Rationale: the test focuses on compilation.
    // A successful compilation indicates that the test case is passed.
}
