import * as mate from "@generated/mate";
import * as nova from "@generated/nova";
import * as pura from "@generated/pura";
import {BusinessError} from "@ohos.base";
import * as System from "std/core/System";

loadLibrary("ani_import");

function main() {
    // Intentially left blank.
    // Rationale: the test focuses on compilation.
    // A successful compilation indicates that the test case is passed.
}
