#!/usr/bin/env python
from subprocess import check_call
from functools import cache


@cache
def get_parser():
    from taihe.TaiheParser import TaiheParser

    return TaiheParser


def get_attr_type(attr_type_name):
    if attr_type_name.endswith("Lst"):
        return f"List['TaiheAST.{attr_type_name[:-3]}']"
    if attr_type_name.endswith("Opt"):
        return f"Optional['TaiheAST.{attr_type_name[:-3]}']"
    return f"Type['TaiheAST.{attr_type_name}']"


def get_attr_pairs(ctx):
    for attr_full_name, attr_ctx in ctx.__dict__.items():
        if attr_full_name[0].isupper() or attr_full_name.startswith("token"):
            attr_type_name, attr_name = attr_full_name.split("_", 1)
            attr_type = get_attr_type(attr_type_name)
            yield attr_type, attr_name


def generate_TaiheAST():
    ast = []
    ast.append(f"from dataclasses import dataclass\n")
    ast.append(f"from typing import List, Optional, Type, Union\n\n")
    ast.append(f"\n")
    ast.append(f"from antlr4 import Token\n")
    ast.append(f"\n")
    ast.append(f"\n")
    ast.append(f"class TaiheAST:\n")
    ast.append(f"    token = Token\n")
    ast.append(f"\n")

    parser = get_parser()
    for rule_name in parser.ruleNames:
        ast_class_name = rule_name[0].upper() + rule_name[1:]
        ctx = getattr(parser, ast_class_name + "Context")(None)
        if rule_name.endswith("Uni"):
            ast.append(f"    {ast_class_name} = Union[\n")
            for attr_type, attr_name in get_attr_pairs(ctx):
                ast.append(f"        {attr_type},\n")
            ast.append(f"    ]\n")
        else:
            ast.append(f"    @dataclass\n")
            ast.append(f"    class {ast_class_name}:\n")
            for attr_type, attr_name in get_attr_pairs(ctx):
                ast.append(f"        {attr_name}: {attr_type}\n")
        ast.append(f"\n")
    ast.pop()
    with open(f"taihe/TaiheAST.py", "w") as file:
        file.writelines(ast)


def generate_TaiheVisitor():
    visitor = []
    visitor.append(f"from taihe.TaiheAST import TaiheAST\n")
    visitor.append(f"\n")
    visitor.append(f"\n")
    visitor.append(f"class TaiheVisitor:\n")
    visitor.append(f"    def visit(self, node):\n")
    visitor.append(
        f"        return getattr(self, 'visit_' + node.__class__.__name__)(node)\n"
    )
    visitor.append(f"\n")
    visitor.append(f"    def visit_token(self, node: TaiheAST.token):\n")
    visitor.append(f"        raise NotImplementedError\n")
    visitor.append(f"\n")
    for rule_name in get_parser().ruleNames:
        ast_class_name = rule_name[0].upper() + rule_name[1:]
        if rule_name.endswith("Uni"):
            continue
        visitor.append(
            f"    def visit_{ast_class_name}(self, node: TaiheAST.{ast_class_name}):\n"
        )
        visitor.append(f"        raise NotImplementedError\n")
        visitor.append(f"\n")
    visitor.pop()
    with open(f"taihe/TaiheVisitor.py", "w") as file:
        file.writelines(visitor)


def run_antlr():
    args = [
        "antlr4",
        "-Dlanguage=Python3",
        "-no-listener",
        "Taihe.g4",
        "-o",
        "taihe",
    ]
    check_call(args)


def main():
    run_antlr()
    generate_TaiheAST()
    generate_TaiheVisitor()


if __name__ == "__main__":
    main()
