#!/usr/bin/env python3

import os
import shutil
import subprocess
from pathlib import Path
import argparse
from taihe.driver import CompilerInstance, CompilerInvocation

CXX = os.getenv("CXX", "clang++")
C = os.getenv("C", "clang")

BASEDIR = Path(__file__).resolve().parent


def run_command(command):
    print(f"+ {command}")
    result = subprocess.run(command, shell=True, check=True, text=True)
    return result


def clean_directory(directory):
    if directory.exists():
        shutil.rmtree(directory)


def create_directory(directory):
    directory.mkdir(parents=True, exist_ok=True)


def copy_directory(src_directory, dst_directory):
    if src_directory.exists():
        shutil.copytree(src_directory, dst_directory, dirs_exist_ok=True)


def compile(output_dir, input_dir, *include_dirs, opt_level):
    output_files = []
    for input_file in input_dir.iterdir():
        name = input_file.name
        output_file = output_dir / f"{name}.o"
        if name.endswith(".c"):
            compiler = C
            std = "gnu11"
        else:
            compiler = CXX
            std = "gnu++17"
        command = f"{compiler} -c -fvisibility=hidden -fPIC -O{opt_level} -std={std} -o {output_file} {input_file}"
        for include_dir in include_dirs:
            command += f" -I {include_dir}"
        run_command(command)
        output_files.append(output_file)
    return output_files


def link(output_file, *input_files, shared, link_options):
    command = f"{CXX} -fPIC -o {output_file}"
    for input_file in input_files:
        command += f" {input_file}"
    for link_option in link_options:
        command += f" {link_option}"
    if shared:
        command += " -shared"
    run_command(command)


def main(
    target_dir: str,
    generate_only: bool,
    generate_and_compile: bool,
    opt_level: str,
    author_link_options: list[str],
    user_link_options: list[str],
    run_args: list[str],
):
    target_path = Path(target_dir)

    idl_dir = target_path / "idl"

    author_dir = target_path / "author"
    author_include_dir = author_dir / "include"
    author_src_dir = author_dir / "src"
    author_generated_dir = target_path / "author_generated"
    author_generated_include_dir = author_generated_dir / "include"
    author_generated_src_dir = author_generated_dir / "src"

    user_dir = target_path / "user"
    user_include_dir = user_dir / "include"
    user_src_dir = user_dir / "src"
    user_generated_dir = target_path / "user_generated"
    user_generated_include_dir = user_generated_dir / "include"
    user_generated_src_dir = user_generated_dir / "src"

    runtime_dir = BASEDIR / ".." / "runtime"
    runtime_include_dir = runtime_dir / "include"
    runtime_src_dir = runtime_dir / "src"

    build_dir = target_path / "build"
    build_runtime_dir = build_dir / "runtime"
    build_author_dir = build_dir / "author"
    build_author_generated_dir = build_dir / "author_generated"
    build_user_dir = build_dir / "user"
    build_user_generated_dir = build_dir / "user_generated"

    so_file = build_dir / "libtest.so"
    elf_file = build_dir / "test"

    if not idl_dir.is_dir():
        raise FileNotFoundError(f"'{idl_dir}' is not an valid directory.")

    clean_directory(author_generated_dir)
    clean_directory(user_generated_dir)
    clean_directory(build_dir)

    create_directory(author_generated_src_dir)
    create_directory(author_generated_include_dir)

    print("Generating author codes...")
    CompilerInstance(
        CompilerInvocation(
            src_dirs=[idl_dir],
            out_dir=author_generated_dir,
            gen_author=True,
            quiet=True,
        )
    ).run()
    print("Done.")

    create_directory(user_generated_src_dir)
    create_directory(user_generated_include_dir)

    print("Generating user codes...")
    CompilerInstance(
        CompilerInvocation(
            src_dirs=[idl_dir],
            out_dir=user_generated_dir,
            gen_user=True,
            quiet=True,
        )
    ).run()
    print("Done.")

    if generate_only:
        return

    create_directory(build_runtime_dir)
    create_directory(build_author_dir)
    create_directory(build_user_dir)
    create_directory(build_author_generated_dir)
    create_directory(build_user_generated_dir)

    print("Compiling to dynamic link library...")
    link(
        so_file,
        *compile(
            build_runtime_dir,
            runtime_src_dir,
            runtime_include_dir,
            opt_level=opt_level,
        ),
        *compile(
            build_author_dir,
            author_generated_src_dir,
            runtime_include_dir,
            author_generated_include_dir,
            opt_level=opt_level,
        ),
        *compile(
            build_author_dir,
            author_src_dir,
            runtime_include_dir,
            author_generated_include_dir,
            author_include_dir,
            opt_level=opt_level,
        ),
        shared=True,
        link_options=author_link_options,
    )
    print("Done.")

    print("Compiling to executable file...")
    link(
        elf_file,
        so_file,
        *compile(
            build_user_dir,
            user_src_dir,
            runtime_include_dir,
            user_generated_include_dir,
            user_include_dir,
            opt_level=opt_level,
        ),
        shared=False,
        link_options=user_link_options,
    )
    print("Done.")

    if generate_and_compile:
        return

    print("Done. Running...")
    run_command(" ".join([str(elf_file), *run_args]))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build and run project from a target directory",
    )
    parser.add_argument(
        "target_directory",
        type=str,
        help="The target directory containing source files for the project",
    )
    parser.add_argument(
        "-g",
        "--generate-only",
        action="store_true",
        help="To generate source and header files and not to compile them",
    )
    parser.add_argument(
        "-c",
        "--generate-and-compile",
        action="store_true",
        help="Generate source and header files and Compile them",
    )
    parser.add_argument(
        "-a",
        "--author-link-options",
        type=str,
        nargs="+",
        default=[],
    )
    parser.add_argument(
        "-u",
        "--user-link-options",
        type=str,
        nargs="+",
        default=[],
    )
    parser.add_argument(
        "-r",
        "--run-args",
        type=str,
        nargs="+",
        default=[],
    )
    parser.add_argument(
        "-O",
        "--optimization",
        type=str,
        nargs="?",
        default="0",
        const="",
        help="Optimization level for compilation",
    )

    args = parser.parse_args()

    main(
        args.target_directory,
        args.generate_only,
        args.generate_and_compile,
        args.optimization,
        args.author_link_options,
        args.user_link_options,
        args.run_args,
    )
