#!/usr/bin/env python3

import argparse
import json
import os
import shutil
import subprocess
import sys
import tarfile
from pathlib import Path

from taihe.driver import CompilerInstance, CompilerInvocation

CXX = os.getenv("CXX", "clang++")
C = os.getenv("C", "clang")

BASEDIR = Path(__file__).resolve().parent


def run_command(command):
    print(f"+ {command}")
    result = subprocess.run(command, shell=True, check=True, text=True)
    return result


def clean_directory(directory):
    if directory.exists():
        shutil.rmtree(directory)


def create_directory(directory):
    directory.mkdir(parents=True, exist_ok=True)


def copy_directory(src_directory, dst_directory):
    if src_directory.exists():
        shutil.copytree(src_directory, dst_directory, dirs_exist_ok=True)


def compile(output_dir, input_dir, *include_dirs, opt_level):
    output_files = []
    for input_file in input_dir.iterdir():
        name = input_file.name
        output_file = output_dir / f"{name}.o"
        if name.endswith(".c"):
            compiler = C
            std = "gnu11"
        else:
            compiler = CXX
            std = "gnu++17"
        command = f"{compiler} -c -fvisibility=hidden -fPIC -O{opt_level} -std={std} -o {output_file} {input_file}"
        for include_dir in include_dirs:
            command += f" -I {include_dir}"
        run_command(command)
        output_files.append(output_file)
    return output_files


def link(output_file, *input_files, shared, link_options):
    command = f"{CXX} -fPIC -o {output_file}"
    for input_file in input_files:
        command += f" {input_file}"
    for link_option in link_options:
        command += f" {link_option}"
    if shared:
        command += " -shared"
    run_command(command)


def compile_abc(output_dir, input_dir, panda_home, config_file_path):
    output_files = []
    if not input_dir.exists() or not input_dir.is_dir():
        return output_files
    for input_file in input_dir.iterdir():
        name = input_file.name
        if name.endswith(".ets"):
            output_file = output_dir / f"{name}.abc"
            command = f"{panda_home}/bin/es2panda {input_file} --output {output_file} --extension ets --arktsconfig {config_file_path}"
            run_command(command)
            command_dump = (
                f"{panda_home}/bin/ark_disasm {output_file} {output_file}.dump"
            )
            run_command(command_dump)
            output_files.append(output_file)
    return output_files


def link_abc(target, *input_files, panda_home):
    command = f"{panda_home}/bin/ark_link --output {target} --"
    for input_file in input_files:
        command += f" {input_file}"
    run_command(command)


def check_local_version(version_file: Path, version: str):
    if version_file.exists():
        with open(version_file) as vf:
            local_version = vf.read().strip()
            return local_version == version
    return False


def download_file(target_file: Path, username: str, password: str, url: str):
    if target_file.exists():
        print(f"already found {target_file}, skipping download")
        return

    try:
        command = [
            "wget",
            "--user",
            username,
            "--password",
            password,
            "--progress=bar:force:noscroll",
            url,
            "-O",
            str(target_file),
        ]
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        print(f"download error: {e}")
        sys.exit(1)


def extract_file(target_file, extract_dir, version_file, version):
    try:
        shutil.rmtree(extract_dir / "package", ignore_errors=True)
        os.makedirs(extract_dir, exist_ok=True)
        with tarfile.open(target_file, "r:gz") as tar:
            tar.extractall(path=extract_dir)
        with open(version_file, "w") as vf:
            vf.write(version)
    except Exception as e:
        print(f"extract error: {e}")
        sys.exit(1)


def download_panda_vm(extract_dir: Path):
    username = "koala-pub"
    password = "y3t!n0therP"

    url = "https://nexus.bz-openlab.ru:10443/repository/koala-npm/%40panda/sdk/-/sdk-1.5.0-dev.25736.tgz"
    target_file = extract_dir / url.split("/")[-1]
    version_file = extract_dir / "version.txt"
    version = target_file.stem

    if not check_local_version(version_file, version):
        download_file(target_file, username, password, url)
        extract_file(target_file, extract_dir, version_file, version)
        print("Complete the download and extract.")


def create_arktsconfig(panda_home, generated_dir, system_dir, config_file_path):
    config_content = {
        "compilerOptions": {
            "baseUrl": str(panda_home),
            "paths": {
                "std": [str(panda_home / "../ets/stdlib/std")],
                "escompat": [str(panda_home / "../ets/stdlib/escompat")],
                "@generated": [str(generated_dir)],
                "@system": [str(system_dir)],
            },
        }
    }
    with open(config_file_path, "w") as json_file:
        json.dump(config_content, json_file, indent=2)
    print(f"A configuration file was created in this path: {config_file_path}")


def main(
    target_dir: str,
    generate_and_compile_ani: bool,
    opt_level: str,
):
    target_path = Path(target_dir).resolve()

    idl_dir = target_path / "idl"

    runtime_dir = BASEDIR / "../runtime"
    runtime_include_dir = runtime_dir / "include"
    runtime_src_dir = runtime_dir / "src"

    author_dir = target_path / "author"
    author_include_dir = author_dir / "include"
    author_src_dir = author_dir / "src"

    generated_dir = target_path / "author_generated"
    generated_include_dir = generated_dir / "include"
    generated_src_dir = generated_dir / "src"

    system_dir = target_path / "system"
    user_dir = target_path / "user"

    build_dir = target_path / "build"

    # cpp build dirs
    build_generated_src_dir = build_dir / "author_generated" / "src"
    build_author_src_dir = build_dir / "author" / "src"
    build_runtime_src_dir = build_dir / "runtime" / "src"

    # ets build dirs
    build_generated_dir = build_dir / "author_generated"
    build_system_dir = build_dir / "system"
    build_user_dir = build_dir / "user"

    if not idl_dir.is_dir():
        raise FileNotFoundError(f"'{idl_dir}' is not an valid directory.")

    clean_directory(generated_dir)
    clean_directory(build_dir)

    print("Generating author and ani codes...")
    CompilerInstance(
        CompilerInvocation(
            src_dirs=[idl_dir],
            out_dir=generated_dir,
            gen_ani=True,
            gen_author=True,
        )
    ).run()
    print("Done.")

    lib_name = target_path.absolute().name

    if generate_and_compile_ani:
        extract_dir = (BASEDIR / "../.panda_vm").resolve()
        extract_dir.mkdir(exist_ok=True)
        download_panda_vm(extract_dir)

        panda_home = extract_dir / "package/linux_host_tools"
        panda_include_dir = panda_home / "../ohos_arm64/include/plugins/ets/runtime/ani"

        create_directory(build_dir)

        create_directory(build_runtime_src_dir)
        create_directory(build_generated_src_dir)
        create_directory(build_author_src_dir)

        so_target = build_dir / f"lib{lib_name}.so"

        link(
            so_target,
            *compile(
                build_runtime_src_dir,
                runtime_src_dir,
                panda_include_dir,
                runtime_include_dir,
                opt_level=opt_level,
            ),
            *compile(
                build_generated_src_dir,
                generated_src_dir,
                panda_include_dir,
                runtime_include_dir,
                generated_include_dir,
                opt_level=opt_level,
            ),
            *compile(
                build_author_src_dir,
                author_src_dir,
                panda_include_dir,
                runtime_include_dir,
                generated_include_dir,
                author_include_dir,
                opt_level=opt_level,
            ),
            shared=True,
            link_options=["-Wl"],
        )

        config_file_path = build_dir / "arktsconfig.json"

        create_arktsconfig(panda_home, generated_dir, system_dir, config_file_path)

        abc_target = build_dir / "main.abc"

        create_directory(build_system_dir)
        create_directory(build_generated_dir)
        create_directory(build_user_dir)

        link_abc(
            abc_target,
            *compile_abc(
                build_generated_dir,
                generated_dir,
                panda_home,
                config_file_path,
            ),
            *compile_abc(
                build_user_dir,
                user_dir,
                panda_home,
                config_file_path,
            ),
            *compile_abc(
                build_system_dir,
                system_dir,
                panda_home,
                config_file_path,
            ),
            panda_home=panda_home,
        )

        run_command(
            f"LD_LIBRARY_PATH={build_dir} "
            f"{panda_home}/bin/ark "
            f"--boot-panda-files={panda_home}/../ets/etsstdlib.abc "
            f"--load-runtimes=ets "
            f"{abc_target} "
            "main.ETSGLOBAL::main"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Build and run project from a target directory",
    )
    parser.add_argument(
        "target_directory",
        type=str,
        help="The target directory containing source files for the project",
    )
    parser.add_argument(
        "-ani",
        "--generate-and-compile-ani",
        action="store_true",
        help="To generate and compile ani files and ets files",
    )
    parser.add_argument(
        "-O",
        "--optimization",
        type=str,
        nargs="?",
        default="0",
        const="",
        help="Optimization level for compilation",
    )

    args = parser.parse_args()

    try:
        main(
            args.target_directory,
            args.generate_and_compile_ani,
            args.optimization,
        )
    except KeyboardInterrupt:
        print("Interrupted. Bye-bye!", file=sys.stderr)
        sys.exit(1)
