#!/usr/bin/env python3

from pathlib import Path
import shutil
import subprocess

C_COPYRIGHT = """/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
"""

SH_COPYRIGHT = """# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""


CLANG_FORMAT_STYLE = r"""BasedOnStyle: Google
---
Language: JavaScript
JavaScriptQuotes: Double
IndentWidth: 4

---
Language:        Cpp
BasedOnStyle:  Google
AccessModifierOffset: -4
AlignAfterOpenBracket: Align
AlignConsecutiveAssignments: false
AlignConsecutiveDeclarations: false
AlignEscapedNewlines: Left
AlignOperands:   true
AlignTrailingComments: true
AllowAllParametersOfDeclarationOnNextLine: true
AllowShortBlocksOnASingleLine: false
AllowShortCaseLabelsOnASingleLine: false
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: true
BinPackArguments: true
BinPackParameters: true
BraceWrapping:   
  AfterClass:      false
  AfterControlStatement: false
  AfterEnum:       false
  AfterFunction:   true
  AfterNamespace:  false
  AfterObjCDeclaration: false
  AfterStruct:     false
  AfterUnion:      false
  AfterExternBlock: false
  BeforeCatch:     false
  BeforeElse:      false
  IndentBraces:    false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
  SplitEmptyNamespace: true
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Custom
BreakBeforeInheritanceComma: false
BreakBeforeTernaryOperators: true
BreakConstructorInitializersBeforeComma: false
BreakConstructorInitializers: BeforeColon
BreakAfterJavaFieldAnnotations: false
BreakStringLiterals: true
ColumnLimit:     120
CommentPragmas:  '^ IWYU pragma:'
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: true
ConstructorInitializerIndentWidth: 4
ContinuationIndentWidth: 4
Cpp11BracedListStyle: true
DerivePointerAlignment: false
DisableFormat:   false
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: true
ForEachMacros:   
  - foreach
  - Q_FOREACH
  - BOOST_FOREACH
IncludeBlocks:   Regroup
IncludeCategories: 
  - Regex:           '^<ext/.*\.h>'
    Priority:        2
  - Regex:           '^<.*\.h>'
    Priority:        1
  - Regex:           '^<.*'
    Priority:        2
  - Regex:           '.*'
    Priority:        3
IncludeIsMainRegex: '([-_](test|unittest))?$'
IndentCaseLabels: true
IndentPPDirectives: None
IndentWidth:     4
IndentWrappedFunctionNames: false
JavaScriptQuotes: Leave
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: false
MacroBlockBegin: ''
MacroBlockEnd:   ''
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
ObjCBlockIndentWidth: 4
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: true
PenaltyBreakAssignment: 2
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakString: 1000
PenaltyExcessCharacter: 1000000
PenaltyReturnTypeOnItsOwnLine: 200
PointerAlignment: Right
ReflowComments:  true
SortIncludes:    false
SortUsingDeclarations: true
SpaceAfterCStyleCast: false
SpaceAfterTemplateKeyword: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: true
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 2
SpacesInAngles:  false
SpacesInContainerLiterals: false
SpacesInCStyleCastParentheses: false
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard:        Cpp11
TabWidth:        4
UseTab:          Never
"""


def should_ignore(file: str) -> bool:
    if file == ".clang-format":
        return True

    if file == "compiler/.pyre_configuration" or file == "compiler/.watchmanconfig":
        return True

    if file.startswith(".githooks") or file.startswith(".github"):
        return True

    return False


def format_code(file_path):
    subprocess.run(
        ["clang-format", "-i", "-style=file", file_path],
        check=True,
    )


def add_c_style_copyright(file_path):
    with open(file_path, "r") as input:
        input_lines = input.readlines()

    output_lines = [C_COPYRIGHT] + input_lines

    with open(file_path, "w") as output:
        output.writelines(output_lines)


def add_sh_style_copyright(file_path):
    with open(file_path, "r") as input:
        input_lines = input.readlines()

    if len(input_lines) and input_lines[0].startswith("#!"):
        output_lines = input_lines[:1] + [SH_COPYRIGHT] + input_lines[1:]
    else:
        output_lines = [SH_COPYRIGHT] + input_lines

    with open(file_path, "w") as output:
        output.writelines(output_lines)


def is_test_file(file: Path):
    try:
        with open(file, "r", encoding="utf-8") as f:
            f.read(1024)
        return True  # 可以作为UTF-8解码，可能是文本文件
    except UnicodeDecodeError:
        return False  # 不能作为UTF-8解码，可能是二进制文件


def process_file(input_path: Path, output_path: Path) -> None:
    print(f"processing '{input_path}' -> '{output_path}'")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    shutil.copy2(input_path, output_path)

    if not is_test_file(input_path):
        return

    if str(input_path).endswith((".cpp", ".c", ".hpp", ".h", ".ts", ".ets")):
        format_code(output_path)

    if str(input_path).endswith(
        (".md", ".json", ".pyre_configuration", ".watchmanconfig")
    ):
        pass
    elif str(input_path).endswith(
        (".taihe", ".cpp", ".c", ".hpp", ".h", ".ets", ".ts", ".g4")
    ):
        add_c_style_copyright(output_path)
    else:
        add_sh_style_copyright(output_path)


def git_get_valid_files():
    result = subprocess.run(
        ["git", "ls-tree", "--full-tree", "-r", "--name-only", "HEAD"],
        capture_output=True,
        text=True,
        check=True,
    )
    directories = result.stdout.strip().split("\n")
    return directories


def git_get_repo_root():
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def main() -> None:
    file_list = git_get_valid_files()
    input_dir = Path(git_get_repo_root())
    output_dir = input_dir / "hw_exported"
    shutil.rmtree(output_dir, ignore_errors=True)
    output_dir.mkdir(parents=True)

    clang_format = output_dir / ".clang-format"
    with open(clang_format, "w") as file:
        file.write(SH_COPYRIGHT + CLANG_FORMAT_STYLE)

    for file in file_list:
        if should_ignore(file):
            continue
        process_file(input_dir / file, output_dir / file)


if __name__ == "__main__":
    main()
