#!/usr/bin/bash

# Test and report code coverage.

source "$(dirname "$0")/common_lib.sh"
init_py_env

coverage run -m -p pytest
coverage run -m -p taihe -I ../test/compiler/idl/ -O ../test/compiler/out/
coverage run -m -p taihe -I ../test/rgb/idl/ -O ../test/rgb/out/
coverage run -m -p taihe -I ../test/string/idl/ -O ../test/string/out/ -u -a
coverage combine
coverage report
