#+TITLE: 接口合约描述语言

* 包

** 定义包
1. 源文件和包一一对应
   - 不支持拆分一个包为多个源文件
   - 也不支持在同一个源文件内描述多个包

2. 包名由源文件名唯一确定
   - 例： =ohos.hardware.sensors.taihe= 源文件内，描述了 =ohos.hardware.sensors= 包下的各个成员

3. 包的成员名称不应和包自身的名称相同
   - 例：若在 =ohos.hardware.sensors= 下定义了 =class SensorManager= ，则不允许定义 =ohos.hardware.sensors.SensorManager.taihe=
   - 理由：JS、Python 等动态类型语言不支持重名

** 使用包管理命名空间
1. 默认可使用当前包下的名称
   #+BEGIN_SRC rust
     // example.types.taihe
     struct Foo {}
     struct Bar {}
     fn func1(bar: example1.Foo): (); // OK
     fn func2(foo: Foo): ();          // OK
   #+END_SRC

2. 可使用 =use= ... =as= 语句导入其他包并生成别名，或使用 =from= ... =use= 语句为其他包下定义的名称生成别名
   #+BEGIN_SRC rust
     // example.test1.taihe
     use example.types as myfoo;
     fn func3(foo: myfoo.Foo);        // OK

     // example.test2.taihe
     from example.types use Bar, Foo as Foobar;
     fn func5(foo: Bar): ();          // OK
     fn func4(foo: Foobar): ();       // OK
   #+END_SRC

3. 包与包之间互相隔离，无从属关系
   #+BEGIN_SRC rust
     // example.taihe
     from types use Foo;                    // Error: package `types` not exist
     use types as mytypes;                  // Error: package `types` not exist
     from example.types use Foo;            // OK
     use example.types;                     // OK
     fn func6(foo: Foo): ();                // OK
     fn func7(foo: example.types.Foo): ();  // OK
   #+END_SRC

* 基础类型
内部提供了以下几种基础类型：
- 无符号整型： =i8=, =i16=, =i32=, =i64=
- 有符号整型： =u8=, =u16=, =u32=, =u64=
- 浮点型： =f32=, =f64=
- 布尔型： =bool=
- 字符串类型： =String=

* 函数
支持在 =class/interface= 以外定义函数

** 函数参数
1. 函数可以有任意数量的参数，每个参数由参数名、参数类型和类型修饰符共同组成。

** 返回值
1. 函数可以有零个或一个返回值。每个返回值由返回值的类型表示。当函数返回值为多个时，可以用结构体表示。

以下是一些合法或非法的函数接口声明示例：
#+BEGIN_SRC rust
function func(m: i32, n: i32): (String, String);  // Error: return value can only be one at most
struct StringPair {
  a: String;
  b: String;
}
function func(m: i32, n: i32): StringPair;        // OK
function func(foo: String);                       // Error: return value type cannot be omitted
function func(foo: i32): void;                    // OK
#+END_SRC

* 结构体
结构体是若干数据成员的组合，其内部可包含的数据成员类型包括基础类型、枚举类型、接口类型和其他结构体类型，其接口声明方法如下：
#+BEGIN_SRC rust
interface Base {}
struct Foo {
  a: i32;
  s: String;
  i: Base;
}
#+END_SRC

* 枚举类
一个基本的枚举类接口定义如下：
#+BEGIN_SRC rust
enum Bar {
  RED = 0;
  GREEN = 1;
  BLUE = 2;
}
#+END_SRC

1. 枚举元素的值可以省略，当省略时，第一个枚举成员的默认值将为零，后续枚举成员的值将在前一成员的值的基础上加一。
#+BEGIN_SRC rust
enum Foo {
  A;        // 0
  B;        // 1
  C = -10;
  D;        // -9
}
#+END_SRC

2. 同一枚举类中的两个不同元素的值不可以相同。
#+BEGIN_SRC rust
enum Foo {
  A = 42;
  B = 42;
}  // Error: Foo::A and Foo::B have the same value

enum Bar {
  A;
  B = -1;
  C;
}  // Error: Bar::A and Bar::C have the same value
   // Bar::A defaults to 0, and Bar::C is implicitly set to 0
#+END_SRC

3. 枚举元素可以定义的类型包括基础类型、枚举类型、接口类型和结构体类型。在使用时枚举类型等同于 =Union= 类型，枚举对象的实际数据类型为其标签值对应的枚举元素类型。
#+BEGIN_SRC rust
enum Color {
  RED   = 0xff << 0o20;
  GREEN = 0xff << 0o10;
  BLUE  = 0xff << 0o00;
}
struct RGB {
  r: u8;
  g: u8;
  b: u8;
}
enum ColorName {
  undefined;            // 0
  color: Color = 0x1;   // 1
  rgb: RGB = 0x2;       // 2
  name: String = 0x3;   // 3
}   // OK
    // if ColorName.tag == 0 : it is same as "?" in "Option" type
    // if ColorName.tag == 1 : ColorName data type is Color
    // if ColorName.tag == 2 : ColorName data type is RGB
    // if ColorName.tag == 3 : ColorName data type is String
#+END_SRC

* 接口
接口的基本定义方式如下：
#+BEGIN_SRC rust
interface BaseA {
  fn baseAFunc(): u32;
}

interface BaseB {
  fn baseBFunc(): u32;
}

interface Derived: BaseA, BaseB {
  fn derivedFunc(): String;
}
#+END_SRC

* 属性
属性的名字和值都是自定义的，基本定义方式如下：
#+BEGIN_SRC rust
[pkgname = "package_func_1", index = 1, has_return_val = FALSE]
function func_1(color: RGB): void;
#+END_SRC

1. 属性可以只有名字，默认值为 =None= 。
#+BEGIN_SRC rust
[tuple]
struct IntPair {
    n: i32;
    m: i32;
}
#+END_SRC

2. 文件可以有且仅有一个属性，定义位置为文件末尾。
#+BEGIN_SRC rust
[file_info = "\u6d4b\u8bd5"]
#+END_SRC

3. 函数、结构体、结构体元素、枚举、枚举元素、接口都可以有且仅有一个属性，定义位置为元素上方相邻的一行。
#+BEGIN_SRC rust
[tuple]                                 // OK
struct IntPair {
    [pkgname = "package", baseinfo]     // OK
    n: i32;
    m: i32;
}
[cname = "package_func_1", index = 1, has_return_val = FALSE]
[cname = "package_func_2", index = 2, has_return_val = FALSE]       // Error
function func(): void;
#+END_SRC

* 其他
1. 函数和类型的声明没有先后顺序，但需要注意结构体之间不可递归包含。例如：
#+BEGIN_SRC rust
struct Foo {
  bar: Bar;
}
struct Bar {
  val: i32;
}  // OK

struct Foo {
  bar: Bar;
}
struct Bar {
  foo: Foo;
}  // Error: recursive inclusion detected: Foo -> bar: Bar -> foo: Foo
#+END_SRC

2. 接口之间不可递归扩展。例如：
#+BEGIN_SRC rust
interface RecursiveIfaceA: RecursiveIfaceB {}
interface RecursiveIfaceB: RecursiveIfaceA {}  // Error
#+END_SRC

3. 枚举与结构体的定义之间不可递归包含。例如：
#+BEGIN_SRC rust
struct RecursiveStruct {
    e: RecursiveEnum;
}
enum RecursiveEnum {
    s: RecursiveStruct;   // Error
}
#+END_SRC
